#!/usr/bin/env python3

import sys
sys.path = ["./mb"] + sys.path

from mudblood import Mudblood

config = {
        "script": None
        }

if len(sys.argv) > 1:
    config['script'] = sys.argv[1]

Mudblood("termbox").run(config)
